<?php
	/* NOTE: On Samurai, the $dbpass password is "samurai" rather than blank */

	/* PLEASE NOTE CAREFULLY: THIS PAGE IS BEING DEPRECIATED BUT WILL REMAIN AS AN EASTER EGG OR
	 * HACKING TARGET. THIS PAGE USED TO BE USED TO SET THE DATABASE CONNECTION INFORMATION SOLELY
	 * BUT IS BEING REPLACED BY THE MySQLHandler CLASS.
	 */

	$dbhost = 'localhost';
	$dbuser = 'mutillidae';
	$dbpass = 'mutillidae';
	$dbname = 'mutillidae';
?>
